#spring:
#  application:
#    name: taolove-ai-agent
#  ai:
#    dashscope:
#      api-key: sk-ws-H.PHMXXEE.qAzb.MEYCIQCzfenIpj8P_eeEoojCkO67UIUnDA87TN0faWJtrNHCSQIhAONMn_7X7H0j1X3C7mOXaPkfUXr5_r7x7G_R_dnbQIC-
#      chat:
#        options:
#          model: qwen-plus
spring:
  application:
    name: taolove-ai-agent
  ai:
    dashscope:
      api-key: sk-ws-H.PHMXXEE.qAzb.MEYCIQCzfenIpj8P_eeEoojCkO67UIUnDA87TN0faWJtrNHCSQIhAONMn_7X7H0j1X3C7mOXaPkfUXr5_r7x7G_R_dnbQIC-
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b